/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;

/**
 *
 * @author USUARIO
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpButtons = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        tflCode = new javax.swing.JTextField();
        tflCode2 = new javax.swing.JTextField();
        tflCode3 = new javax.swing.JTextField();
        tflTittle = new javax.swing.JTextField();
        tflTittle2 = new javax.swing.JTextField();
        tflTittle3 = new javax.swing.JTextField();
        tflAuthor = new javax.swing.JTextField();
        tflAuthor2 = new javax.swing.JTextField();
        tflAuthor3 = new javax.swing.JTextField();
        lblCode = new javax.swing.JLabel();
        lblTittle = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        rbtCode = new javax.swing.JRadioButton();
        rbtTittle = new javax.swing.JRadioButton();
        rbtAuthor = new javax.swing.JRadioButton();
        pnlSearch = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLineal = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBinary = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlResult = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        pnlResult2 = new javax.swing.JPanel();
        lblResult2 = new javax.swing.JLabel();
        pnlResult3 = new javax.swing.JPanel();
        lblResult3 = new javax.swing.JLabel();
        pnlColor = new javax.swing.JPanel();
        lblResult1 = new javax.swing.JLabel();
        pnlVerVector = new javax.swing.JPanel();
        lblResult4 = new javax.swing.JLabel();
        pnlLimpiar = new javax.swing.JPanel();
        lblResult5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Búsqueda Binaria");
        setMaximumSize(new java.awt.Dimension(800, 520));
        setMinimumSize(new java.awt.Dimension(800, 520));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));

        tittle.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        tittle.setForeground(new java.awt.Color(0, 0, 204));
        tittle.setText("Buscador de libros");

        tflCode.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        tflCode.setForeground(new java.awt.Color(0, 0, 204));
        tflCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflCodeActionPerformed(evt);
            }
        });

        tflTittle.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        tflTittle.setForeground(new java.awt.Color(0, 0, 204));

        tflAuthor.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        tflAuthor.setForeground(new java.awt.Color(0, 0, 204));

        lblCode.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        lblCode.setForeground(new java.awt.Color(0, 0, 204));
        lblCode.setText("Código");

        lblTittle.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(0, 0, 204));
        lblTittle.setText("Título");

        lblAuthor.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        lblAuthor.setForeground(new java.awt.Color(0, 0, 204));
        lblAuthor.setText("Autor");

        pnlSearch.setBackground(new java.awt.Color(0, 0, 204));
        pnlSearch.setForeground(new java.awt.Color(255, 255, 255));
        pnlSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSearch.setBackground(new java.awt.Color(255, 255, 255));
        lblSearch.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 20)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setText("¡Realizar Búsquedas!");

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        tblLineal.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        tblLineal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Iteración", "Inicio", "Medio", "Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLineal);
        if (tblLineal.getColumnModel().getColumnCount() > 0) {
            tblLineal.getColumnModel().getColumn(0).setResizable(false);
            tblLineal.getColumnModel().getColumn(1).setResizable(false);
            tblLineal.getColumnModel().getColumn(2).setResizable(false);
            tblLineal.getColumnModel().getColumn(3).setResizable(false);
        }

        tblBinary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Iteración", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBinary);
        if (tblBinary.getColumnModel().getColumnCount() > 0) {
            tblBinary.getColumnModel().getColumn(0).setResizable(false);
            tblBinary.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Número de iteraciones: ");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Número de iteraciones: ");

        pnlResult.setBackground(new java.awt.Color(0, 0, 204));
        pnlResult.setForeground(new java.awt.Color(255, 255, 255));
        pnlResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblResult.setBackground(new java.awt.Color(255, 255, 255));
        lblResult.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 16)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 255));
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setText("Primer resultado");

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlResult2.setBackground(new java.awt.Color(0, 0, 204));
        pnlResult2.setForeground(new java.awt.Color(255, 255, 255));
        pnlResult2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblResult2.setBackground(new java.awt.Color(255, 255, 255));
        lblResult2.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 16)); // NOI18N
        lblResult2.setForeground(new java.awt.Color(255, 255, 255));
        lblResult2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult2.setText("Segundo resultado");

        javax.swing.GroupLayout pnlResult2Layout = new javax.swing.GroupLayout(pnlResult2);
        pnlResult2.setLayout(pnlResult2Layout);
        pnlResult2Layout.setHorizontalGroup(
            pnlResult2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlResult2Layout.setVerticalGroup(
            pnlResult2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlResult3.setBackground(new java.awt.Color(0, 0, 204));
        pnlResult3.setForeground(new java.awt.Color(255, 255, 255));
        pnlResult3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblResult3.setBackground(new java.awt.Color(255, 255, 255));
        lblResult3.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 16)); // NOI18N
        lblResult3.setForeground(new java.awt.Color(255, 255, 255));
        lblResult3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult3.setText("Tercer resultado");

        javax.swing.GroupLayout pnlResult3Layout = new javax.swing.GroupLayout(pnlResult3);
        pnlResult3.setLayout(pnlResult3Layout);
        pnlResult3Layout.setHorizontalGroup(
            pnlResult3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlResult3Layout.setVerticalGroup(
            pnlResult3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlColor.setBackground(new java.awt.Color(0, 0, 204));
        pnlColor.setForeground(new java.awt.Color(255, 255, 255));
        pnlColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblResult1.setBackground(new java.awt.Color(255, 255, 255));
        lblResult1.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 16)); // NOI18N
        lblResult1.setForeground(new java.awt.Color(255, 255, 255));
        lblResult1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult1.setText("Color");

        javax.swing.GroupLayout pnlResult1Layout = new javax.swing.GroupLayout(pnlColor);
        pnlColor.setLayout(pnlResult1Layout);
        pnlResult1Layout.setHorizontalGroup(
            pnlResult1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        pnlResult1Layout.setVerticalGroup(
            pnlResult1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlVerVector.setBackground(new java.awt.Color(0, 0, 204));
        pnlVerVector.setForeground(new java.awt.Color(255, 255, 255));
        pnlVerVector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblResult4.setBackground(new java.awt.Color(255, 255, 255));
        lblResult4.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 16)); // NOI18N
        lblResult4.setForeground(new java.awt.Color(255, 255, 255));
        lblResult4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult4.setText("Ver vector");

        javax.swing.GroupLayout pnlResult4Layout = new javax.swing.GroupLayout(pnlVerVector);
        pnlVerVector.setLayout(pnlResult4Layout);
        pnlResult4Layout.setHorizontalGroup(
            pnlResult4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        pnlResult4Layout.setVerticalGroup(
            pnlResult4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlLimpiar.setBackground(new java.awt.Color(0, 0, 204));
        pnlLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        pnlLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblResult5.setBackground(new java.awt.Color(255, 255, 255));
        lblResult5.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 16)); // NOI18N
        lblResult5.setForeground(new java.awt.Color(255, 255, 255));
        lblResult5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult5.setText("Limpiar");

        javax.swing.GroupLayout pnlResult5Layout = new javax.swing.GroupLayout(pnlLimpiar);
        pnlLimpiar.setLayout(pnlResult5Layout);
        pnlResult5Layout.setHorizontalGroup(
            pnlResult5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult5, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        pnlResult5Layout.setVerticalGroup(
            pnlResult5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResult5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(tittle))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(tflCode, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(tflTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(tflAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblCode)
                .addGap(12, 12, 12)
                .addComponent(tflCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(rbtCode)
                .addGap(31, 31, 31)
                .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tflTittle2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(rbtTittle)
                .addGap(39, 39, 39)
                .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tflAuthor2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(rbtAuthor))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(tflCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(tflTittle3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(tflAuthor3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(216, 216, 216)
                .addComponent(jLabel2))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnlResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlResult2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlResult3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnlColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(pnlVerVector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(pnlLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tittle)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tflCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tflTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tflAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCode))
                    .addComponent(tflCode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(rbtCode))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblTittle))
                    .addComponent(tflTittle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(rbtTittle))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblAuthor))
                    .addComponent(tflAuthor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(rbtAuthor)))
                .addGap(3, 3, 3)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tflCode3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tflTittle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tflAuthor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlResult2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlResult3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlVerVector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tflCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflCodeActionPerformed

    public ButtonGroup getGrpButtons() {
        return grpButtons;
    }

    public JLabel getLblAuthor() {
        return lblAuthor;
    }

    public JLabel getLblCode() {
        return lblCode;
    }

    public JLabel getLblResult() {
        return lblResult;
    }

    public JLabel getLblResult1() {
        return lblResult1;
    }

    public JLabel getLblResult2() {
        return lblResult2;
    }

    public JLabel getLblResult3() {
        return lblResult3;
    }

    public JLabel getLblResult4() {
        return lblResult4;
    }

    public JLabel getLblResult5() {
        return lblResult5;
    }

    public JLabel getLblSearch() {
        return lblSearch;
    }

    public JLabel getLblTittle() {
        return lblTittle;
    }

    public JPanel getPnlResult() {
        return pnlResult;
    }

    public JPanel getPnlColor() {
        return pnlColor;
    }

    public JPanel getPnlResult2() {
        return pnlResult2;
    }

    public JPanel getPnlResult3() {
        return pnlResult3;
    }

    public JPanel getPnlVerVector() {
        return pnlVerVector;
    }

    public JPanel getPnlLimpiar() {
        return pnlLimpiar;
    }

    public JPanel getPnlSearch() {
        return pnlSearch;
    }

    public JRadioButton getRbtAuthor() {
        return rbtAuthor;
    }

    public JRadioButton getRbtCode() {
        return rbtCode;
    }

    public JRadioButton getRbtTittle() {
        return rbtTittle;
    }

    public JTable getTblBinary() {
        return tblBinary;
    }

    public JTable getTblLineal() {
        return tblLineal;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JTextField getTflAuthor() {
        return tflAuthor;
    }

    public JTextField getTflAuthor2() {
        return tflAuthor2;
    }

    public JTextField getTflAuthor3() {
        return tflAuthor3;
    }

    public JTextField getTflCode() {
        return tflCode;
    }

    public JTextField getTflCode2() {
        return tflCode2;
    }

    public JTextField getTflCode3() {
        return tflCode3;
    }

    public JTextField getTflTittle() {
        return tflTittle;
    }

    public JTextField getTflTittle2() {
        return tflTittle2;
    }

    public JTextField getTflTittle3() {
        return tflTittle3;
    }

    public JLabel getTittle() {
        return tittle;
    }

    /**
     * @param args the command line arguments
     */

    // Getters


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.ButtonGroup grpButtons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblResult1;
    private javax.swing.JLabel lblResult2;
    private javax.swing.JLabel lblResult3;
    private javax.swing.JLabel lblResult4;
    private javax.swing.JLabel lblResult5;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JPanel pnlColor;
    private javax.swing.JPanel pnlResult2;
    private javax.swing.JPanel pnlResult3;
    private javax.swing.JPanel pnlVerVector;
    private javax.swing.JPanel pnlLimpiar;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JRadioButton rbtAuthor;
    private javax.swing.JRadioButton rbtCode;
    private javax.swing.JRadioButton rbtTittle;
    private javax.swing.JTable tblBinary;
    private javax.swing.JTable tblLineal;
    private javax.swing.JTextField tflAuthor;
    private javax.swing.JTextField tflAuthor2;
    private javax.swing.JTextField tflAuthor3;
    private javax.swing.JTextField tflCode;
    private javax.swing.JTextField tflCode2;
    private javax.swing.JTextField tflCode3;
    private javax.swing.JTextField tflTittle;
    private javax.swing.JTextField tflTittle2;
    private javax.swing.JTextField tflTittle3;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
